### ISSUE TITLE
Error with pywrap and sympy

### ISSUE THREAD

**Issue by jverzani** [stevengj/PyCall.jl#131]
With the latest development version of Julia and the newest PyCall, I get an error when I try `@pyimport sympy` that happens in the `pywrap` call. The message is:

```
ERROR: TypeError: instantiate_type: expected TypeConstructor, got Function 
in pywrap at /Users/verzani/.julia/v0.4/PyCall/src/PyCall.jl:331
in pywrap at /Users/verzani/.julia/v0.4/PyCall/src/PyCall.jl:318
```

It does work with julia version 3. Is this something that can be fixed or something to work around?

**Comment by stevengj** [comment]
I can reproduce.  Hmm, probably another casualty of the tupocolypse, since it works with a 0.4 that is a few days older. 

I'm guessing that one of the `consts...` expressions in `pywrap` is now problematic.  You could try `eval`-ing them one by one in a loop to see which one barfs.  (SymPy doesn't define a variable named `Tuple` by any chance?)

**Comment by jverzani** [comment]
That's it. If I add "Tuple" to the `reserved` set then pywrap will work.

**Comment by stevengj** [comment]
Thanks.  (Some blessed day, when `.` is overloadable, all of this anonymous-module cruft will go away.  The module will just be a `PyObject` and `.` will look up the module member at runtime.)

**Comment by jverzani** [comment]
Thanks!
