### ISSUE TITLE
Problems with calling method

### ISSUE THREAD

**Issue by akaFalsh** [stevengj/PyCall.jl#141]
The continuing of the issue #137 .

I still have problems with calling another method.

getDataDescription call went ok. However when I try to call getNumberOfCells in the same manner it returns another error:
```
numcells = dd[:getNumberOfCells]
ERROR: key not found: "getNumberOfCells"

numcells = dd["getNumberOfCells"]
ERROR: key not found: "getNumberOfCells"

numcells = dd.getNumberOfCells()
ERROR: type PyObject has no field getNumberOfCells
```

The description of an object dd says:
```
PyObject <bound method ModelPtr.getDataDescription of <model.ModelPtr; proxy of <Swig Object of type 'org::model::ModelPtr *' at 0x8d5a180> >>
```

**Comment by stevengj** [comment]
`dd` is a bound method, not an object.  Presumably you need to call it before you get an object that you has a `getNumberOfCells` field.  e.g. `pycall(dd, PyObject)[:getNumberOfCells]()`.  (I added the final `()` because I'm guessing that `getNumberOfCells` is also a method.

(Presumably it is the same in Python.)

**Comment by stevengj** [comment]
None of these seem to be actual problems in PyCall, just questions about how to use it.
