### ISSUE TITLE
False AttributeError.

### ISSUE THREAD

**Issue by Ismael-VC** [stevengj/PyCall.jl#164]
I was trying to answer this question at StackOverflow:

* http://stackoverflow.com/questions/31261350/automatically-generate-ijulia-notebooks

So I try to use `PyCall`:

* http://nbviewer.ipython.org/gist/Ismael-VC/4c4fcee41b8761af9673

And I get this error at `Out [7]`:
```
PyError (:PyObject_Call) <type 'exceptions.AttributeError'>
AttributeError("'dict' object has no attribute 'worksheets'",)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbformat/current.py", line 188, in write
    s = writes(nb, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbformat/current.py", line 154, in writes
    return versions[version].writes_json(nb, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbformat/v3/nbjson.py", line 48, in writes
    nb = split_lines(nb)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbformat/v3/rwbase.py", line 85, in split_lines
    for ws in nb.worksheets:

while loading In[7], in expression starting on line 3

 in pyerr_check at /home/juser/.julia/v0.3/PyCall/src/exception.jl:58
 in pycall at /home/juser/.julia/v0.3/PyCall/src/PyCall.jl:91
 in fn at /home/juser/.julia/v0.3/PyCall/src/conversions.jl:188
 in anonymous at In[7]:4
 in open at iostream.jl:137
```

But the dictionary in question indeed does have a `worksheets` key, as can be seen at `Out [8] `.

**Comment by stevengj** [comment]
The dict has an `"worksheets"` *key*, but not a worksheets *attribute*.  

I think the problem here may be that the conversion to a Julia `Dict` is losing some Python info.  Try using lower-level functions that give you more control over the type conversions:
```jl
nbf = pyimport("IPython.nbformat.current")
nb = pycall(nbf["new_notebook"], PyDict)
```
or even `nb = pycall(nbf["new_notebook"], PyObject)`

**Comment by Ismael-VC** [comment]
@stevengj I did what you told me, but now in this part: 

```
fname = "test.ipynb"

open(fname, "w") do f
    nbf[:write](nb, f, "ipynb")
end
```

I have this error:

```
PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError("'unicode' does not have the buffer interface",)
  File "/usr/local/lib/python2.7/dist-packages/IPython/nbformat/current.py", line 191, in write
    return fp.write(s)

while loading In[6], in expression starting on line 3

 in pyerr_check at /home/juser/.julia/v0.3/PyCall/src/exception.jl:58
 in pycall at /home/juser/.julia/v0.3/PyCall/src/PyCall.jl:91
 in fn at /home/juser/.julia/v0.3/PyCall/src/conversions.jl:188
 in anonymous at In[6]:4
 in open at iostream.jl:137
```

I don't know hot to convert an `ASCIIString` into a normal Python string (not unicode). I tried aliasing `python` with `python3` and also this:

```julia
function PyCall.PyObject(s::ASCIIString)
    PyCall.@pyinitialize
    PyObject(PyCall.@pycheckn ccall(pystring_fromstring,
                                 PyPtr, (Ptr{Uint8},), bytestring(s)))
end
```

but then I get:

```julia
PyObject(ascii("test"))

s not defined
while loading In[15], in expression starting on line 1

 in PyObject at In[12]:88
```

I haven't been able to figure out why.

**Comment by yuyichao** [comment]
@Ismael-VC I checked the python source and AFAICT the issue is not passing a bytestring to python, rather python is passing a string (unicode) to julia and julia don't know how to write it to the file object.

My working example [here](https://github.com/yuyichao/explore/blob/c33c4297493c930d3568c50cfcf57dcf8730abcf/julia/ijulia-generate/Generate.ipynb)

Also note that the interface is deprecated (You can see the deprecation warning from a ipython notebook) and AFAICT it is encouraged to specify the version of the notebook format directly.

**Comment by yuyichao** [comment]
Also, to convert a python `str` to `bytes` you can do what you would do in python, i.e. calling `encode` on it.

**Comment by stevengj** [comment]
See also http://stackoverflow.com/questions/25115042/typeerror-unicode-does-not-have-the-buffer-interface
