### ISSUE TITLE
datatype conversion error in opencv function

### ISSUE THREAD

**Issue by FrankWessels** [stevengj/PyCall.jl#233]
Well, I might have found another issue. Spent several hours trying to pinpoint the cause, but I am fairly new to julia, thus perhaps you can help me.

In julia:
```
using ImageMagick, Images, ImageView, PyCall
cv2 = pyimport("cv2")
@pyimport numpy as np

img = cv2[:imread]("image.png")
img = cv2[:cvtColor](img, cv2[:COLOR_BGR2GRAY])
img = cv2[:GaussianBlur](img,(1,1),1)
img = cv2[:adaptiveThreshold](img,255,0,1,5,2)
im2, contours, hierarchy = cv2[:findContours](img, cv2[:RETR_LIST], cv2[:CHAIN_APPROX_SIMPLE])

gave me

LoadError: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('Layout of the output array image is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)',)

while it work fine in python

import cv2, numpy as np

img = cv2.imread("image.png")
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img = cv2.GaussianBlur(img,(1,1),1)
img = cv2.adaptiveThreshold(img,255,0,1,5,2)
im2, contours, hierarchy = cv2.findContours(img, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
contours[1]
```
I found out the function findContours is the problem and is not accepting the image. From opencv I learned that it accepts "an 8-bit single-channel image". I tried to convert the image type and a lot of other things.

**Comment by stevengj** [comment]
It sounds like `findContours` wants a row-major array, whereas the `img` return values by default are converted to Julia column-major arrays.

You could preventing it from converting `img` to a Julia object during processing.  e.g. do `img = pycall(cv2[:imread], PyObject, "image.png")`, where the `PyObject` argument tells it to leave the return value as the unconverted raw Python object.  (Or use `PyArray` instead of `PyObject` to create a Julia array-like wrapper around a Numpy array, assuming cv2 is using Numpy.)

**Comment by FrankWessels** [comment]
Got it to work. Not sure if this is a real issue for PyCall anyway, but the ability of using pyobjects helps me a great deal. Thx!

**Comment by stevengj** [comment]
It's a general tradeoff of automated conversions.  Automated conversions to Julia types are usually convenient, but it occasionally gives you a different type from what you want, in which case you have to switch to `pycall(function, desired type, args...)`
