### ISSUE TITLE
Can PyObject works for arbitrary types by treating them as tuple?

### ISSUE THREAD

**Issue by colinfang** [stevengj/PyCall.jl#253]
Is it plausible to have a default PyObject constructor & default convert that works for any custom types, by treating them as tuples? So in python, they are tuples or even namedtuple or simple class .

```{julia}
immutable B
    x::Int
    y::Int
end

immutable A
    x::B
    y::Int
end
```

So a user doesn't have to write a new converter for those simple composite types.

**Comment by stevengj** [comment]
I don't know whether we would want to do that by default, but it would certainly be possible to write such a thing, e.g.
```jl
function pytuple{T}(x::T)
    fields = fieldnames(T)
    isempty(fields) && throw(ArgumentError("..."))
    return PyObject(ntuple(i -> getfield(x, fields[i]), length(fields))
end
```
However, it's not clear to me what the use case is for such a thing.   Mostly, PyCall is used for calling Python libraries, and why would a Python library want a tuple version of a Julia type?

**Comment by colinfang** [comment]
It is used for argument passing.

For example, if we have a python function

```{python}
 def calc(x) :
    return x.a + x.b * 3
```

And I have a Julia object

```{julia}
immutable A
    x::Int
    y::Int
end
```

So I can simply use the python function `calc(A(1,2))` without having to do any extra work.

**Comment by stevengj** [comment]
Yes, but why would you have a function like that?  Normally, if a Python function in a library wants to work on a type `Foo` that has some internal fields like `a` and `b`, you should just construct a Python `Foo` object (via `pythonmodule.Foo(a, b)` in Julia) rather than trying to construct a Julia object to mirror the Python one.

 Can you give a realistic example, e.g. an existing Python library that you would want to call in this way?

**Comment by stevengj** [comment]
On the other hand, defining a "true" Python class (with methods, inheritance, etc) from Julia is quite useful.  See #250 for a much full-featured way to do this, hopefully soon to be merged.
