### ISSUE TITLE
Do we need to pyincref here?

### ISSUE THREAD

**Issue by colinfang** [stevengj/PyCall.jl#261]
I am investigating a Segmentation Fault possibly because of `py_decref` issue.

```
--> Start pydecref: ps=PyObject NULL"
"Start pydecref 140082311589056: js=jL_Function_call|kw_"

signal (11): Segmentation fault
```

The line `kw = PyDict{Symbol,PyAny}(PyObject(kw_))` looks suspecious.
We borrowed a `PyPtr`, don't we need to `pyincref` it?

It also aplies to line `args = PyObject(args_)`

```{julia}
function jl_Function_call(self_::PyPtr, args_::PyPtr, kw_::PyPtr)
    ret_ = convert(PyPtr, C_NULL)
    args = PyObject(args_)
    try
        f = unsafe_pyjlwrap_to_objref(self_)::Function
        if kw_ == C_NULL
            ret = PyObject(f(convert(PyAny, args)...))
        else
            kw = PyDict{Symbol,PyAny}(PyObject(kw_))
            kwargs = [ (k,v) for (k,v) in kw ]
            ret = PyObject(f(convert(PyAny, args)...; kwargs...))
        end
        ret_ = ret.o
        ret.o = convert(PyPtr, C_NULL) # don't decref
    catch e
        pyraise(e)
    finally
        args.o = convert(PyPtr, C_NULL) # don't decref
    end
    return ret_::PyPtr
end
```

**Comment by stevengj** [comment]
Good catch.  I think you're right.  The Python API manual is [unclear on this point](https://docs.python.org/2/c-api/intro.html#reference-count-details) because it doesn't document the case of `tp_call` or other callback functions specifically.   However, looking [at the source code of PyObject_Call](https://github.com/python/cpython/blob/8565eb659812740b228b132c42dd45f76cf144fa/Objects/abstract.c#L2149-L2175) clearly indicates that the parameters are "borrowed" references, i.e. we aren't supposed to decref them.

**Comment by stevengj** [comment]
The `args` is actually safe because of the `args.o = NULL` in the `finally` clause.  I just forgot to handle the `kw` case.
