### ISSUE TITLE
pyimport_conda doesn't recognise the Anaconda installation

### ISSUE THREAD

**Issue by cortner** [stevengj/PyCall.jl#278]
This is a follow-up from [Conda.jl Issue #1](https://github.com/Luthaf/Conda.jl/issues/1)

cortner: thanks. so I could go the other way round, use
```
try 
     pyimport_conda("<pip name>", "<conda name>")
catch
    run(`conda install some package`)
end
```
that way, if the package is already installed, I won't install it again?

stevengj: the pyimport_conda function does the conda install for you if needed. That's the whole point.

Note that this is documented in the PyCall README ... no need to read the PyCall source code

(Note that the first argument of pyimport_conda is the name of the module you want to import; it has nothing to do with pip.)

@stevengj I tried to use`pyimport_conda`, but without success:

```
julia> Pkg.build("PyCall")
INFO: Building PyCall
INFO: PyCall is using /Users/ortner/anaconda/bin/python (Python 2.7.11) at /Users/ortner/anaconda/bin/python, libpython = /Users/ortner/anaconda/lib/libpython2.7.dylib

julia> PyCall.pyimport_conda("pyamg", "pyamg")
ERROR: Failed to import required Python module pyamg.

For automated pyamg installation, try configuring PyCall to use the Conda Python distribution within Julia.  Relaunch Julia and run:
    ENV["PYTHON"]=""
    Pkg.build("PyCall")
before trying again.
#  and some more
```

But I specifically don't want to use the miniconda distribution. I also tried it with first setting
```
julia> ENV["PYTHON"] = "/Users/ortner/anaconda/bin/python"
"/Users/ortner/anaconda/bin/python"
```

Where is my mistake? Thank you.

**Comment by stevengj** [comment]
`pyimport_conda` is currently for when PyCall is using the Conda.jl "private" miniconda distro, not any generic system-wide Anaconda installation.

I suppose I could extend it to the latter case.   But how do we reliably detect if Python comes from Anaconda, and find the corresponding `conda` program?

**Comment by cortner** [comment]
I I think I must have misunderstood your comment in the Conda.jl Issue #1. 

In my case, when I build `PyCall` it automatically detects it. Is it not possible to check whether `PyCall` is already configured to use an existing Anaconda installation? In that case `conda` should be in the path anyhow? Sorry if this is naive.

I am perfectly happy to just tell the user to install it by hand. Can I then suggest though to change the error message as follows:
```
julia> PyCall.pyimport_conda("pyamg", "pyamg")
ERROR: Failed to import required Python module pyamg.

First install pyamg for your Python distribution (***can PyCall say here what it currently uses?***).

Alternatively, for automated pyamg installation, try configuring PyCall to use the Conda Python distribution within Julia. (***warning on what this entails?***) Relaunch Julia and run:
    ENV["PYTHON"]=""
    Pkg.build("PyCall")
before trying again. 
#  and some more
```
This can probably be formulated better, but the gist is that a naive user (like me) might read the error message too quickly and accidentally switch her/his Python distribution to Conda.jl/miniconda.

Thanks.

**Comment by stevengj** [comment]
`PyCall.pyprogramname` is the Python executable name that your PyCall was configured to use.  `PyCall.conda == true` if you are using Conda.jl's Python.

Whether `conda` is in the path is, in principle, independent of whether PyCall was configured to use Anaconda Python, because you can build PyCall with the full path of any Python via `ENV["PYTHON"]="/path/to/python"; Pkg.build("PyCall")`.   For example, just a few minutes ago I was doing some testing and configured it to use `/usr/bin/python` on a system that *also* had a global Anaconda Python in the PATH and *also* had Conda.jl.   So you can't just check for `conda` in the path.

**Comment by cortner** [comment]
of for me, as I say above it is perfectly fine to expect a user who maintains their own Python distribution to do these installations by hand. But I did need to read the error message twice before I understood it, so this could maybe be improved. I'll close this.

**Comment by stevengj** [comment]
Let me re-open this, because I think it is feasible to automate the installation for a global Anaconda install, and the prospect is worth considering.

In particular, it looks like we can detect Anaconda's Python from the Python version string, via `contains(bytestring(ccall(@pysym(:Py_GetVersion), Ptr{UInt8}, ())), "Anaconda")` (`true` for Anaconda).  Then we could get the `conda` path via `joinpath(dirname(PyCall.pyprogramname), "conda")`

**Comment by stevengj** [comment]
Weird, I pushed a commit to fix this but it is not showing up in the Github history (although it shows up if I `git clone` a fresh copy).

**Comment by stevengj** [comment]
Okay, the commit finally showed up.

**Comment by stevengj** [comment]
@cortner, let me know if this fixes your concern.

**Comment by stevengj** [comment]
(You will need to do `Pkg.checkout("PyCall")` to get this patch until a new version of PyCall is tagged.)

**Comment by cortner** [comment]
Done. Works beautifully. Thank you!
